# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PhgH9WKG6Q_AQIufSZi6K7ocqGprRP2H
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

def main():
    # --- TASK 1: Setup ---
    # Load the data generated in Task 3
    file_path = "data/trends_analyzed.csv"
    if not os.path.exists(file_path):
        print("Data file not found. Did you run Task 3?")
        return

    df = pd.read_csv(file_path)

    # Create the outputs folder if it doesn't exist
    if not os.path.exists("outputs"):
        os.makedirs("outputs")
        print("Created 'outputs/' folder.")

    # Setting a clean style for all plots
    plt.style.use('ggplot')

    # --- TASK 2: Chart 1 - Top 10 Stories by Score ---
    # We sort by score and take the top 10
    top_10 = df.sort_values(by='score', ascending=False).head(10)

    # Logic to shorten titles so they don't break the layout
    top_10['short_title'] = top_10['title'].apply(lambda x: x[:47] + '...' if len(x) > 50 else x)

    plt.figure(figsize=(10, 6))
    plt.barh(top_10['short_title'], top_10['score'], color='skyblue')
    plt.gca().invert_yaxis() # Highest score at the top
    plt.title('Top 10 Trending Stories by Score')
    plt.xlabel('Upvote Score')
    plt.ylabel('Story Title')
    plt.tight_layout()
    plt.savefig('outputs/chart1_top_stories.png')
    plt.show()

    # --- TASK 3: Chart 2 - Stories per Category ---
    cat_counts = df['category'].value_counts()

    plt.figure(figsize=(8, 6))
    # Using a list of colors to make the bars distinct
    colors = ['tomato', 'cornflowerblue', 'gold', 'mediumseagreen', 'orchid']
    cat_counts.plot(kind='bar', color=colors)
    plt.title('Distribution of Stories per Category')
    plt.xlabel('Category')
    plt.ylabel('Number of Stories')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('outputs/chart2_categories.png')
    plt.show()

    # --- TASK 4: Chart 3 - Score vs Comments ---
    plt.figure(figsize=(8, 6))

    # We split the data based on the 'is_popular' boolean we made in Task 3
    popular = df[df['is_popular'] == True]
    not_popular = df[df['is_popular'] == False]

    plt.scatter(not_popular['score'], not_popular['num_comments'], color='gray', label='Standard', alpha=0.6)
    plt.scatter(popular['score'], popular['num_comments'], color='orange', label='Popular', edgecolors='red')

    plt.title('Correlation: Score vs. Comments')
    plt.xlabel('Score')
    plt.ylabel('Number of Comments')
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig('outputs/chart3_scatter.png')
    plt.show()

    # --- BONUS: Dashboard ---
    # Creating a 2x2 grid (leaving one slot empty)
    fig, axes = plt.subplots(2, 2, figsize=(15, 12))
    fig.suptitle('TrendPulse Dashboard', fontsize=20, fontweight='bold')

    # Slot 1: Top Stories
    axes[0, 0].barh(top_10['short_title'], top_10['score'], color='skyblue')
    axes[0, 0].invert_yaxis()
    axes[0, 0].set_title('Top 10 Stories')

    # Slot 2: Category Bar
    cat_counts.plot(kind='bar', color=colors, ax=axes[0, 1])
    axes[0, 1].set_title('Stories per Category')

    # Slot 3: Scatter Plot
    axes[1, 0].scatter(not_popular['score'], not_popular['num_comments'], color='gray', alpha=0.5)
    axes[1, 0].scatter(popular['score'], popular['num_comments'], color='orange')
    axes[1, 0].set_title('Score vs Comments')

    # Hide the unused 4th subplot
    axes[1, 1].axis('off')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig('outputs/dashboard.png')
    plt.show()

    print("All charts and dashboard saved successfully in the 'outputs/' folder!")

if __name__ == "__main__":
    main()