# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zoYRFHBHSBrfA5kr3JnErLpLBVnfNGNX
"""

import pandas as pd
import numpy as np
import os

def main():
    # --- TASK 1: Load and Explore ---
    file_path = "data/trends_clean.csv"

    if not os.path.exists(file_path):
        print(f"Error: {file_path} not found. Please run Task 2 first!")
        return

    # Loading the cleaned data
    df = pd.read_csv(file_path)

    print("--- First 5 Rows of Data ---")
    print(df.head())

    print(f"\nDataFrame Shape: {df.shape}") # (Rows, Columns)

    # Calculating basic averages using Pandas
    avg_score = df['score'].mean()
    avg_comments = df['num_comments'].mean()
    print(f"Average Score: {avg_score:.2f}")
    print(f"Average Comments: {avg_comments:.2f}")

    # --- TASK 2: Basic Analysis with NumPy ---
    print("\n--- Statistical Analysis (NumPy) ---")

    # Converting columns to NumPy arrays for calculations
    scores_array = df['score'].to_numpy()

    print(f"Mean Score: {np.mean(scores_array):.2f}")
    print(f"Median Score: {np.median(scores_array)}")
    print(f"Standard Deviation: {np.std(scores_array):.2f}")
    print(f"Highest Score: {np.max(scores_array)}")
    print(f"Lowest Score: {np.min(scores_array)}")

    # Finding the category with the most stories
    # idxmax() on a value count gives the label of the highest frequency
    top_category = df['category'].value_counts().idxmax()
    print(f"Category with most stories: {top_category}")

    # Finding the story with the most comments
    max_comments_idx = df['num_comments'].idxmax()
    most_commented_title = df.loc[max_comments_idx, 'title']
    most_commented_count = df.loc[max_comments_idx, 'num_comments']
    print(f"Most Commented Story: '{most_commented_title}' with {most_commented_count} comments")

    # --- TASK 3: Add New Columns ---

    # 1. Engagement: Discussion per upvote (we add 1 to avoid dividing by zero)
    df['engagement'] = df['num_comments'] / (df['score'] + 1)

    # 2. Is Popular: Boolean check against the average
    df['is_popular'] = df['score'] > avg_score

    print("\nNew columns 'engagement' and 'is_popular' have been added.")

    # --- TASK 4: Save the Result ---
    output_path = "data/trends_analyzed.csv"
    df.to_csv(output_path, index=False)
    print(f"Analysis complete. Results saved to {output_path}")

if __name__ == "__main__":
    main()