# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVC26zBa1fl3ppStJCm76BUBTT9xJwr_
"""

import pandas as pd
import os
import glob

def main():
    # --- TASK 1: Load the JSON File ---
    data_folder = "data"
    # We look for any JSON file in the data folder
    json_files = glob.glob(os.path.join(data_folder, "*.json"))

    if not json_files:
        print("Error: No JSON files found in the data/ folder. Please run Task 1 first.")
        return

    # Picking the most recently created JSON file to be safe
    input_file = max(json_files, key=os.path.getctime)

    # Reading JSON into a Pandas DataFrame
    df = pd.read_csv = pd.read_json(input_file)
    print(f"Loaded {len(df)} stories from {input_file}")

    # --- TASK 2: Clean the Data ---

    # 1. Duplicates: Every post_id should be unique
    df = df.drop_duplicates(subset=['post_id'])
    print(f"After removing duplicates: {len(df)}")

    # 2. Missing values: Essential fields must exist
    # 'how=any' drops a row if any of these specific columns are null
    df = df.dropna(subset=['post_id', 'title', 'score'])
    print(f"After removing nulls: {len(df)}")

    # 3. Data types: Ensure numbers are actually integers
    # fillna(0) prevents errors if there are empty comment fields
    df['score'] = df['score'].astype(int)
    df['num_comments'] = df['num_comments'].fillna(0).astype(int)

    # 4. Low quality: Filter out stories with score < 5
    df = df[df['score'] >= 5]
    print(f"After removing low scores: {len(df)}")

    # 5. Whitespace: Cleaning up the titles
    # .str.strip() removes leading/trailing spaces
    df['title'] = df['title'].str.strip()

    # --- TASK 3: Save as CSV ---
    output_path = os.path.join(data_folder, "trends_clean.csv")
    df.to_csv(output_path, index=False)

    print(f"Saved {len(df)} rows to {output_path}")

    # Quick Summary: How many stories made the cut for each topic?
    print("\nStories per category:")
    print(df['category'].value_counts())

if __name__ == "__main__":
    main()